# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kdRRa-6J1YiB4oBvN-jN5S-x-nnubha
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Mall_Customers.csv")

df

plt.scatter(df["Annual Income (k$)"], df["Spending Score (1-100)"])
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.show

x = df.iloc[: , 3:].values
x

plt.scatter(x[:, 0], x[:, 1])
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.show()

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
wcss = [] #to save wcss values
k = range(2, 15)

for i in k:
  model_wcss = KMeans(n_clusters=i, random_state=0)
  model_wcss.fit(x)
  y_wcss = model_wcss.predict(x)
  wcss.append(model_wcss.inertia_)
  plt.bar(i, silhouette_score(x, y_wcss))

plt.scatter(k, wcss)
plt.plot(k, wcss)

model = KMeans(n_clusters=2, random_state=0)
model.fit(x)
y = model.fit_predict(x)
y

import numpy as np
np.unique(y, return_counts=True)

fig = plt.figure()
ax = fig.add_subplot(111)
for i in range(2):
  ax.scatter(x[y==i, 0], x[y==i, 1])
ax.scatter(model.cluster_centers_[:,0],
          model.cluster_centers_[:,1], s=200, c='red')

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(df["Annual Income (k$)"], df["Spending Score (1-100)"], df["Age"])

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
x = df.iloc[:, 2:].values
wcss = [] #to save wcss values
k = range(2, 15)

for i in k:
  model_wcss = KMeans(n_clusters=i, random_state=0)
  model_wcss.fit(x)
  y_wcss = model_wcss.predict(x)
  wcss.append(model_wcss.inertia_)
  plt.bar(i, silhouette_score(x, y_wcss))

plt.scatter(k, wcss)
plt.plot(k, wcss)

from sklearn.cluster import KMeans
model= KMeans(n_clusters=6, random_state=0)
y = model.fit_predict(x)
y

import numpy as np
np.unique(y, return_counts=True)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
for i in range(6):
  ax.scatter(x[y==i, 0], x[y==i, 1], x[y==i, 2])
ax.scatter(model.cluster_centers_[:,0],
          model.cluster_centers_[:,1],
          model.cluster_centers_[:,2], s=200, c='red')

