# -*- coding: utf-8 -*-
"""KMeanClustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1saE056sNhcGM49B1l5WbSFN-ci43OV5A
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

digits = load_digits()
digits

X = digits.data

y = digits.target

print(X.shape)

fig, axes = plt.subplots(2, 5, figsize=(10, 4))

for i, ax in enumerate(axes.flat):
    ax.imshow(digits.images[i], cmap='gray')
    ax.set_title(f"Label: {digits.target[i]}")
    ax.axis('off')

plt.show()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

wcss = []

for i in range(1, 15):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 15), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

kmeans = KMeans(n_clusters=10, random_state=42)
y_mean = kmeans.fit_predict(X_scaled)

centers = kmeans.cluster_centers_
fig, axes = plt.subplots(2, 5, figsize=(10, 4))

for i, ax in enumerate(axes.flat):
  ax.imshow(centers[i].reshape(8,8), cmap='gray')
  ax.set_title(f"Cluster {i}")
  ax.axis('off')

plt.show()

from scipy.stats import mode
labels = np.zeros_like(y_mean)

for i in range(10):
  mask = (y_mean ==i)
  labels[mask] = mode(y[mask])[0]

accuracy = np.sum(labels == y) / len(y)
print("Accuracy: ", accuracy)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_mean, cmap='tab10')
plt.title("Clusters in 2D (PCA)")
plt.show()

for cluster in range(3):
    images = X[y_mean == cluster][:10]
    for img in images:
        plt.imshow(img.reshape(8,8), cmap='gray')
        plt.show()

